# Generated by Django 4.1.2 on 2022-11-12 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_manager', '0001_initial'),
        ('item_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_pricing', models.CharField(max_length=60)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_manager.customer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_manager.item')),
            ],
        ),
    ]
