# Generated by Django 4.1.2 on 2022-11-12 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
        ('customer_manager', '0001_initial'),
        ('item_manager', '0001_initial'),
        ('customer_pricing_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('invoice_number', models.CharField(default='00000', max_length=60)),
                ('customer_name', models.CharField(default='00000', max_length=60)),
                ('po_num_row_1', models.CharField(default='00000', max_length=60)),
                ('po_num_row_2', models.CharField(default='00000', max_length=60)),
                ('po_num_row_3', models.CharField(default='00000', max_length=60)),
                ('po_num_row_4', models.CharField(default='00000', max_length=60)),
                ('po_num_row_5', models.CharField(default='00000', max_length=60)),
                ('item_num_row_1', models.CharField(default='00000', max_length=60)),
                ('item_num_row_2', models.CharField(default='00000', max_length=60)),
                ('item_num_row_3', models.CharField(default='00000', max_length=60)),
                ('item_num_row_4', models.CharField(default='00000', max_length=60)),
                ('item_num_row_5', models.CharField(default='00000', max_length=60)),
                ('item_name_row_1', models.CharField(default='00000', max_length=60)),
                ('item_name_row_2', models.CharField(default='00000', max_length=60)),
                ('item_name_row_3', models.CharField(default='00000', max_length=60)),
                ('item_name_row_4', models.CharField(default='00000', max_length=60)),
                ('item_name_row_5', models.CharField(default='00000', max_length=60)),
                ('customer_pricing_ea_row_1', models.CharField(default='00000', max_length=60)),
                ('customer_pricing_ea_row_2', models.CharField(default='00000', max_length=60)),
                ('customer_pricing_ea_row_3', models.CharField(default='00000', max_length=60)),
                ('customer_pricing_ea_row_4', models.CharField(default='00000', max_length=60)),
                ('customer_pricing_ea_row_5', models.CharField(default='00000', max_length=60)),
                ('qty_ea_row_1', models.CharField(default='00000', max_length=60)),
                ('qty_ea_row_2', models.CharField(default='00000', max_length=60)),
                ('qty_ea_row_3', models.CharField(default='00000', max_length=60)),
                ('qty_ea_row_4', models.CharField(default='00000', max_length=60)),
                ('qty_ea_row_5', models.CharField(default='00000', max_length=60)),
                ('amount_row_1', models.CharField(default='00000', max_length=60)),
                ('amount_row_2', models.CharField(default='00000', max_length=60)),
                ('amount_row_3', models.CharField(default='00000', max_length=60)),
                ('amount_row_4', models.CharField(default='00000', max_length=60)),
                ('amount_row_5', models.CharField(default='00000', max_length=60)),
                ('invoice_sales_amount', models.CharField(default='00000', max_length=60)),
                ('invoice_freight_amount', models.CharField(default='00000', max_length=60)),
                ('invoice_total_due', models.CharField(default='00000', max_length=60)),
                ('invoice_age', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('invoice_customer_check_number', models.CharField(default='00000', max_length=60)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_manager.company')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_manager.customer')),
                ('customer_pricing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_pricing_manager.customer_pricing')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_manager.item')),
            ],
        ),
    ]
