# Generated by Django 4.1.2 on 2022-11-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
    ]
